theme = ['hugo-video', 'hugo-simple']

baseURL = 'https://etiand.re'
languageCode = 'en-us'
title = "Étienne's blog"
copyright = "© 2024 Étienne André"

enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

[params]
math = true
title = "Hugo Simple"
description = "Hugo Simple Demo"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = false

[params.author]
name = "Étienne André"
email = "eti.andre@gmail.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 20

[[menu.main]]
name = "Publications"
pageRef = "/publications"
weight = 30

[[menu.main]]
name = "Resume"
pageRef = "/resume"
weight = 40


[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
